In [5]:
display_labels = ['Thought-terminatingcliché', 'Slogans', 'Reductioadhitlerum', 'CausalOversimplification', 'Obfuscation', 'Bandwagon', 'Exaggeration/Minimisation', 'Repetition', 'PresentingIrrelevantData(RedHerring)', 'Confusion', '"MisrepresentationofSomeonesPosition(StrawMan)"', 'Flag-waving', 'Doubt', 'Glitteringgeneralities(Virtue)', 'Appealtoauthority', 'Appealtofear/prejudice', 'LoadedLanguage', 'Intentionalvagueness', 'Whataboutism', 'Black-and-whiteFallacy/Dictatorship', 'Namecalling/Labeling', 'Smears']

In [44]:
from main import load_semeval2024
from feature_extraction.feature_extraction import load_data_split

train, test = load_semeval2024()

train = load_data_split(train)


train_features, test_features = map(extract_features_for_loader, [train_loader, test_loader])    
train_labels = train_dataset["label"].fillna("None").str.split(",").to_numpy()
test_labels = test_dataset["label"].fillna("None").str.split(",").to_numpy()

,text,label
0,THIS IS WHY YOU NEED\n\nA SHARPIE WITH YOU AT ...,Black-and-whiteFallacy/Dictatorship
1,GOOD NEWS!\n\nNAZANIN ZAGHARI-RATCLIFFE AND AN...,"LoadedLanguage,Glitteringgeneralities(Virtue)"
2,PAING PHYO MIN IS FREE!,NaN
3,Move your ships away!\n\noooook\n\nMove your s...,NaN
4,"WHEN YOU'RE THE FBI, THEY LET YOU DO IT.",Thought-terminatingcliché
...,...,...
6995,If your doctor prescribes you medication witho...,"LoadedLanguage,CausalOversimplification,Though..."
6996,DEFENDS TRUMP. \nMADE ALLEGATIONS OF ELECTION ...,"LoadedLanguage,Whataboutism"
6997,I'm having trouble selling our incredibly enor...,NaN
6998,I'm so happy we live in a world without slaver...,NaN


In [6]:
import pandas as pd
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
import numpy as np

x = np.array([[12, 13, 14], [12, 12, 13], [0, 0, 0]])
y = ([["C","B"],["A"], ["B"]])

# y.shape[-1]

In [7]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer(classes=["A", "B", "C"])
train_labels_binarized = mlb.fit_transform(y)

mlb.inverse_transform(train_labels_binarized)
#mlb.classes_.shape[-1]

[('B', 'C'), ('A',), ('B',)]

In [8]:
mlb.classes_

array(['A', 'B', 'C'], dtype=object)

In [50]:
train_labels_binarized

array([[1, 1, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [53]:

lr = LinearRegression()

num_labels = mlb.classes_.shape[-1]
preds = []

for idx in range(num_labels):
    lr.fit(X=x, y=train_labels_binarized.transpose()[idx])
    print(f"Trained with: \n{x} \nand {idx+1} feature, wich was\n {train_labels_binarized.transpose()[idx]}")
    pred_for_feature = lr.predict([[11, 12, 9], [9, 1, 0]])
    #print(pred_for_feature)
    preds.append(pred_for_feature)

np.array(preds).transpose()


Trained with: 
[[12 13 14]
 [12 12 13]
 [ 0  0  0]] 
and 1 feature, wich was
 [1 1 0]
Trained with: 
[[12 13 14]
 [12 12 13]
 [ 0  0  0]] 
and 2 feature, wich was
 [1 0 1]
Trained with: 
[[12 13 14]
 [12 12 13]
 [ 0  0  0]] 
and 3 feature, wich was
 [0 0 0]


array([[ 0.90311419, -0.69204152,  0.        ],
       [ 0.74394464, -8.5432526 ,  0.        ]])